export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'

export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'

export const UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS'

export const UPDATE_MOVIES_FAILURE ='UPDATE_MOVIES_FAILURE'




